use_frameworks!

platform :ios, '9.0'

target 'JanstiPriLib_Example' do
  pod 'JanstiPriLib', :path => '../'

  target 'JanstiPriLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
